### ISSUE TITLE
Allow configuring custom remote

### ISSUE THREAD

**Issue by sseneca** [lyarenei/jellyfin-plugin-listenbrainz#17]
I'm trying to scrobble to my [Maloja](https://github.com/krateng/maloja) instance, which supports acting like a listenbrainz remote:

> You can also use any scrobbler that allows you to set a custom Listenbrainz or GNUFM server. See API.md for details.

**Comment by lyarenei** [comment]
@sseneca I was finally able to release a new plugin version, please check it out. 
`2.2.1.0` if you use JF 10.8, `1.4.1.0` if you use JF 10.7.
Please note that in order to apply new URLs, you will need to restart the server: https://github.com/lyarenei/jellyfin-plugin-listenbrainz#global-configuration

Let me know if you find any issues, thanks.
