### ISSUE TITLE
BUG: data not properly recorded in listenbrainz

### ISSUE THREAD

**Issue by HeuristicPerson** [lyarenei/jellyfin-plugin-listenbrainz#33]
Not 100% sure, but I'd say this is an issue that started to happen with the recent changes in musicbrainz/listenbrainz websites.

It seems not all the data is recorded in listenbrainz when using the jellyfin addon. So far these are my findings:

1. Playing music from jellyfin's web gui: everything working fine
2. Playing music from Gelli (Android client), or Fintunes, the currently playing track is recorded, but it's not added to the "recent listens" list once they are complete.
3. Playing music from Finamp (Android client), currently playing track or fully played tracks not recorded at all.

Anybody else with the same issue?

I'm using:

Server: docker_jellyfin
Version: 10.8.9
Operating System: Linux
Architecture: X64

Listenbrainz addon: Listenbrainz 2.3.0.1

**Comment by lyarenei** [comment]
Hi, this is not really a bug, it's due to how this plugin detects playbacks eligible for submission to ListenBrainz. 

Unfortunately, as you found out, Finamp and Gelli do not send stop command to the server - which this plugin expects in default recognition mode. 

Both players have open issues for this, however, without any resolution:
- [Gelli issue](https://github.com/dkanada/gelli/issues/143)
- [Finamp issue](https://github.com/jmshrv/finamp/issues/87)

You can try enabling [user-data detection mode](https://github.com/lyarenei/jellyfin-plugin-listenbrainz#userdata-approach) in the plugin. If these clients at least mark items as played in the Jellyfin library, you should see the data being recorded.

Both the default and alternative mode have their advantages and disadvantages, described [here](https://github.com/lyarenei/jellyfin-plugin-listenbrainz#alternative-listen-recognition).

Apart from the Jellyfin Web, another client, Symfonium, should be working as well. Though for that one, you need to enable the mentioned alternative detection mode. Fintunes has also added support recently, but it looks like there it still has not been released.

**Comment by HeuristicPerson** [comment]
Many thanks for the comprehensive explanation, lyarenei. I'lll give a go to your suggested clients.

Regards
